#!/usr/bin/env bash

BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

git submodule init -- ${BASEDIR}/pkgs/stowsh
STOWSH=${BASEDIR}/pkgs/stowsh/bin/stowsh

$STOWSH --dot-prefix -t "$HOME" "$@" "$BASEDIR/configuration"
